/**
 * File: trench_mod.js
 * Description/README:
 *   Trench Pickaxe (Green) mod for Minecraft Java 1.8.8 style JS mod loaders (Optifine / Eaglercraft-like).
 *   Single-file mod implementing:
 *     - Trench Pickaxe progression: wooden -> stone -> iron -> gold -> diamond
 *     - Trench Enchanter (retextured enchantment table) with point-based custom enchant system and sliders
 *     - Custom recipes and assets references
 *
 * Asset filenames (place under your mod assets folder):
 *   - items:
 *       assets/trenchmod/textures/items/trench_pickaxe_wood.png
 *       assets/trenchmod/textures/items/trench_pickaxe_stone.png
 *       assets/trenchmod/textures/items/trench_pickaxe_iron.png
 *       assets/trenchmod/textures/items/trench_pickaxe_gold.png
 *       assets/trenchmod/textures/items/trench_pickaxe_diamond.png
 *       assets/trenchmod/textures/items/trench_gem_green.png
 *   - blocks:
 *       assets/trenchmod/textures/blocks/trench_enchanter.png
 *       assets/trenchmod/textures/blocks/trench_enchanter_book.png
 *   - gui:
 *       (optional) assets/trenchmod/textures/gui/trench_enchanter_bg.png
 *
 * Suggested placement:
 *   - Put textures under: assets/trenchmod/textures/{items,blocks,gui}/...
 *   - Put model/json files mirroring standard Minecraft names if needed for your loader.
 *
 * Recipes (in human-readable form; also registered programmatically below):
 *   - trench_gem_green: glass + emerald + green dye
 *       shaped 3x3:
 *         G D G
 *         D E D
 *         G D G
 *       (G=glass, D=green dye, E=emerald)  -> 1x trench_gem_green
 *
 *   - Trench Pickaxe recipes (shaped like a normal pickaxe but with trench_gem_green in center)
 *     Wooden Trench Pickaxe:
 *       W W W
 *       0 T 0
 *       0 S 0
 *       (W=wood plank, T=trench_gem_green, S=stick)
 *     Stone/Iron/Gold/Diamond substitute head material.
 *
 *   - Trench Enchanter:
 *       B E B
 *       E T E
 *       B G B
 *       (B=bookshelf, E=enchanting_table, T=trench_gem_green, G=green dye) -> 1x trench_enchanter
 *
 * Important notes:
 *   - Diamond maxPoints formula implemented exactly as: maxPoints = 20 * number_of_custom_enchants * 0.5
 *     With default 8 enchants: 20 * 8 * 0.5 = 80 points for diamond pickaxe.
 *   - Wooden = 5 points. Intermediate materials scale linearly between wood (index=1) and diamond (index=5).
 *     Example formula in code: points = woodPoints + (diamondPoints-woodPoints) * ((tierIndex-1)/(4))
 *
 * Compatibility:
 *   - This file uses generic pseudo-API calls in a JS style often used by 1.8.8 JS mod loaders:
 *       registerItem(id, props), registerBlock(id, props), addShapedRecipe(output, pattern, key),
 *       onBlockHarvested(callback), openGui(player, gui), sendMessage(player, text), getPlayerYawPitch(player),
 *       getPlayerPos(player), rayTraceFromPlayer(player, maxDist), breakBlock(world, x,y,z,dropItems),
 *       getBlockAt(world,x,y,z), setBlockAt(world,x,y,z,block), dropXp(world,x,y,z,amount)
 *
 *   - If your loader uses different names, adapt the mapping in the "API ADAPTER" section below.
 *
 * Usage:
 *   - Drop this file into your mod folder (example: mods/trench_mod.js).
 *   - Place textures into the assets paths listed above (or adapt the paths in the top comments).
 *   - Restart the server/client. Craft trench_gem_green, then craft Trench Pickaxes and the Trench Enchanter.
 *
 * Limitations:
 *   - This mod performs multi-block breaking in a single event and will attempt to respect block harvestability.
 *   - On some servers you may need operator privileges or permission adaptation for bulk-break events.
 *
 * Author: Generated by ChatGPT (as requested)
 * License: You may use/modify freely for private servers/modpacks. Attribution appreciated.
 */

/* =========================
   CONFIG & CONSTANTS
   ========================= */

const MODID = "trenchmod"; // used in asset paths and NBT keys
const NUMBER_OF_CUSTOM_ENCHANTS = 8; // default; change if you add more enchant definitions below

// Material tiers: index 1..5 (wood, stone, iron, gold, diamond)
const MATERIAL_TIERS = [
  null,
  { id: "wood", display: "Wooden", durability: 59, harvestLevel: 0, tierIndex: 1 },
  { id: "stone", display: "Stone", durability: 131, harvestLevel: 1, tierIndex: 2 },
  { id: "iron", display: "Iron", durability: 250, harvestLevel: 2, tierIndex: 3 },
  { id: "gold", display: "Gold", durability: 32, harvestLevel: 0, tierIndex: 4 },
  { id: "diamond", display: "Diamond", durability: 1561, harvestLevel: 3, tierIndex: 5 }
];

// Trench dimensions per material (explicit numbers requested)
const TRENCH_DIMENSIONS = {
  wood:   { x: 3, y: 3, z: 3 },   // Wooden: 3×3×3
  stone:  { x: 5, y: 4, z: 5 },   // Stone: 5×4×5
  iron:   { x: 9, y: 6, z: 9 },   // Iron: 9×6×9
  gold:   { x: 11, y: 7, z: 11 }, // Gold: 11×7×11
  diamond:{ x: 16, y: 8, z: 16 }  // Diamond: 16×8×16
};

// Enchant budget rules
const WOOD_MAX_POINTS = 5;
const DIAMOND_MAX_POINTS = 20 * NUMBER_OF_CUSTOM_ENCHANTS * 0.5; // EXACT formula: 20 * N * 0.5
// Confirm numeric value (calculated): for N=8 => 80
// Scaling formula: points = WOOD_MAX_POINTS + (DIAMOND_MAX_POINTS - WOOD_MAX_POINTS) * ((tierIndex - 1) / (5-1))

// List of custom enchant definitions (minimum 8 implemented)
const CUSTOM_ENCHANTS = [
  {
    id: "trenching",
    name: "Trenching",
    shortDesc: "Increase horizontal trench spread.",
    maxLevel: 5,
    costPerLevel: 2,
    // effect: increases effective horizontal dimensions when applied (we'll factor into trench box)
  },
  {
    id: "depth_guard",
    name: "Depth Guard",
    shortDesc: "Prevents dangerous drops while trenching.",
    maxLevel: 3,
    costPerLevel: 3,
    // effect: checks would-be holes and skip blocks that cause unsafe drops beyond a threshold
  },
  {
    id: "vein_seek",
    name: "Vein Seek",
    shortDesc: "Better chance to break connected ore veins in the trench.",
    maxLevel: 4,
    costPerLevel: 4
  },
  {
    id: "fortitude",
    name: "Fortitude",
    shortDesc: "Reduces durability drain per block.",
    maxLevel: 3,
    costPerLevel: 5
  },
  {
    id: "echo_scrape",
    name: "Echo Scrape",
    shortDesc: "Telegraphs nearby ores with particles.",
    maxLevel: 3,
    costPerLevel: 3
  },
  {
    id: "overclock",
    name: "Overclock",
    shortDesc: "Increases mining speed while trenching.",
    maxLevel: 4,
    costPerLevel: 4
  },
  {
    id: "conserve",
    name: "Conserve",
    shortDesc: "Converts some broken blocks into XP instead of items.",
    maxLevel: 2,
    costPerLevel: 6
  },
  {
    id: "anchor",
    name: "Anchor",
    shortDesc: "Prevents breaking blocks that would break certain structures.",
    maxLevel: 2,
    costPerLevel: 6
  }
];

// Mapping for items and blocks (IDs used in registration)
const IDS = {
  trench_gem_green: "trenchmod:trench_gem_green",
  trench_enchanter: "trenchmod:trench_enchanter",
  pickaxes: {
    wood:   "trenchmod:trench_pickaxe_wood",
    stone:  "trenchmod:trench_pickaxe_stone",
    iron:   "trenchmod:trench_pickaxe_iron",
    gold:   "trenchmod:trench_pickaxe_gold",
    diamond:"trenchmod:trench_pickaxe_diamond"
  }
};

/* =========================
   API ADAPTER / NOTES
   =========================
   Adapt these helper wrappers to the actual mod loader API.
   Example mapping comments (pseudocode):
     - registerItem(id, props) -> yourLoader.registerItem({id: id, name: ..., texture: ...})
     - registerBlock(id, props) -> yourLoader.registerBlock(...)
     - addShapedRecipe(output, pattern, key) -> yourLoader.addRecipe(...)
     - onBlockHarvested(callback) -> events.on('blockBreak', callback)
     - openGui(player, guiDef) -> network.sendToClient(player, 'openGui', guiDef)
   The code below uses these wrapper names; implement or replace them for your platform.
*/

/* -------------------------
   SIMPLE GENERIC HELPERS
   ------------------------- */

// Note: These are pseudo-implementations to show structure. Replace with your platform's real APIs.
function registerItem(id, props) {
  // props: {displayName, texture, maxStackSize, toolMaterial, onUse}
  if (typeof __registerItem === "function") {
    __registerItem(id, props);
  } else {
    // Fallback / debug log
    console.log("registerItem", id, props);
  }
}

function registerBlock(id, props) {
  if (typeof __registerBlock === "function") {
    __registerBlock(id, props);
  } else {
    console.log("registerBlock", id, props);
  }
}

function addShapedRecipe(output, pattern, key) {
  if (typeof __addRecipe === "function") {
    __addRecipe(output, pattern, key);
  } else {
    console.log("addShapedRecipe", output, pattern, key);
  }
}

function onBlockHarvested(callback) {
  if (typeof __onBlockHarvested === "function") {
    __onBlockHarvested(callback);
  } else if (typeof events !== "undefined" && events.onBlockHarvested) {
    events.onBlockHarvested(callback);
  } else {
    // console fallback
    console.log("onBlockHarvested handler registered (pseudo).");
  }
}

function openGui(player, guiDef) {
  if (typeof __openGui === "function") {
    __openGui(player, guiDef);
  } else {
    // Try to send via network packet or console log
    console.log("openGui for", player, guiDef.title);
  }
}

function sendMessage(player, text) {
  if (typeof __sendMessage === "function") {
    __sendMessage(player, text);
  } else {
    console.log("[MSG to " + player + "]: " + text);
  }
}

function getPlayerPos(player) {
  if (typeof __getPlayerPos === "function") return __getPlayerPos(player);
  return { x: player.x || 0, y: player.y || 64, z: player.z || 0 };
}

function getPlayerYawPitch(player) {
  if (typeof __getPlayerYawPitch === "function") return __getPlayerYawPitch(player);
  return { yaw: player.yaw || 0, pitch: player.pitch || 0 };
}

function rayTraceFromPlayer(player, maxDist) {
  if (typeof __rayTraceFromPlayer === "function") return __rayTraceFromPlayer(player, maxDist);
  // Simple fallback: compute forward vector from yaw/pitch and return an endpoint
  const pos = getPlayerPos(player);
  const yp = getPlayerYawPitch(player);
  // Convert degrees to radians
  const yawRad = (yp.yaw) * Math.PI / 180;
  const pitchRad = (yp.pitch) * Math.PI / 180;
  const dx = -Math.sin(yawRad) * Math.cos(pitchRad);
  const dy = -Math.sin(pitchRad);
  const dz = Math.cos(yawRad) * Math.cos(pitchRad);
  return { from: pos, to: { x: pos.x + dx * maxDist, y: pos.y + dy * maxDist, z: pos.z + dz * maxDist } };
}

/* =========================
   ITEM / BLOCK REGISTRATION
   ========================= */

(function registerEverything() {
  // Register trench_gem_green
  registerItem(IDS.trench_gem_green, {
    displayName: "Trench Gem (Green)",
    texture: MODID + ":items/trench_gem_green.png",
    maxStackSize: 64
  });

  // Register pickaxes
  Object.keys(IDS.pickaxes).forEach(matKey => {
    const id = IDS.pickaxes[matKey];
    const mat = MATERIAL_TIERS[
      matKey === "wood" ? 1 :
      matKey === "stone" ? 2 :
      matKey === "iron" ? 3 :
      matKey === "gold" ? 4 :
      5
    ];
    registerItem(id, {
      displayName: "Trench Pickaxe (Green) - " + mat.display,
      texture: MODID + ":items/trench_pickaxe_" + mat.id + ".png",
      toolMaterial: mat.id,
      // We'll use metadata/NBT to store enchant info and current durability.
      maxDurability: mat.durability,
      onUse: function(event) {
        // Optional: hook when right-clicking with the pickaxe (e.g., toggle trench mode). Placeholder.
      }
    });
  });

  // Register Trench Enchanter block (retextured enchantment table)
  registerBlock(IDS.trench_enchanter, {
    displayName: "Trench Enchanter (Green)",
    texture: MODID + ":blocks/trench_enchanter.png",
    overlayBookTexture: MODID + ":blocks/trench_enchanter_book.png",
    hardness: 5.0
  });

  // Register recipes
  addShapedRecipe({ id: IDS.trench_gem_green, count: 1 },
    [
      "G D G",
      "D E D",
      "G D G"
    ],
    {
      G: { item: "minecraft:glass" },
      D: { item: "minecraft:dye", meta: 2 }, // green dye often meta 2 in 1.8
      E: { item: "minecraft:emerald" }
    });

  // Pickaxe recipes (wood, stone, iron, gold, diamond) - shaped like a pickaxe with trench gem center
  addShapedRecipe({ id: IDS.pickaxes.wood, count: 1 },
    ["WWW", "0T0", "0S0"], { W: { item: "minecraft:planks" }, T: { item: IDS.trench_gem_green }, S: { item: "minecraft:stick" } });

  addShapedRecipe({ id: IDS.pickaxes.stone, count: 1 },
    ["SSS", "0T0", "0S0"], { S: { item: "minecraft:cobblestone" }, T: { item: IDS.trench_gem_green }, "0": null });

  addShapedRecipe({ id: IDS.pickaxes.iron, count: 1 },
    ["III", "0T0", "0S0"], { I: { item: "minecraft:iron_ingot" }, T: { item: IDS.trench_gem_green }, S: { item: "minecraft:stick" } });

  addShapedRecipe({ id: IDS.pickaxes.gold, count: 1 },
    ["GGG", "0T0", "0S0"], { G: { item: "minecraft:gold_ingot" }, T: { item: IDS.trench_gem_green }, "0": null });

  addShapedRecipe({ id: IDS.pickaxes.diamond, count: 1 },
    ["DDD", "0T0", "0S0"], { D: { item: "minecraft:diamond" }, T: { item: IDS.trench_gem_green }, "0": null });

  // Trench Enchanter recipe
  addShapedRecipe({ id: IDS.trench_enchanter, count: 1 },
    ["B E B", "E T E", "B D B"], {
      B: { item: "minecraft:bookshelf" },
      E: { item: "minecraft:enchanting_table" },
      T: { item: IDS.trench_gem_green },
      D: { item: "minecraft:dye", meta: 2 } // green dye
    });

})();

/* =========================
   NBT / ITEM METADATA HELPERS
   ========================= */

function getPickaxeData(itemStack) {
  // Reads enchant metadata from itemStack.nbt or returns defaults
  itemStack._nbt = itemStack._nbt || {};
  const nbt = itemStack._nbt;
  nbt.trench = nbt.trench || {};
  nbt.trench.enchants = nbt.trench.enchants || {}; // map enchantId -> level
  nbt.trench.durability = (typeof nbt.trench.durability === "number") ? nbt.trench.durability : itemStack.maxDurability || 0;
  return nbt.trench;
}

function setPickaxeData(itemStack, trenchData) {
  itemStack._nbt = itemStack._nbt || {};
  itemStack._nbt.trench = trenchData;
}

/* =========================
   ENCHANTMENT UI DEFINITION
   ========================= */

// GUI is defined as a JS object description. Adapt the structure for your loader's GUI system.
function createTrenchEnchanterGui(player, heldItem) {
  // Compute max points for the pickaxe based on its material
  const matId = heldItem.toolMaterial || "wood";
  const tier = MATERIAL_TIERS[
    matId === "wood" ? 1 :
    matId === "stone" ? 2 :
    matId === "iron" ? 3 :
    matId === "gold" ? 4 :
    5
  ];
  const maxPoints = computeMaxPointsForTier(tier.tierIndex);
  const currentData = getPickaxeData(heldItem);

  // GUI model: title, list of enchants, sliders, apply/cancel
  const gui = {
    title: "Trench Enchanter (Green)",
    subtitle: "Points: 0 / " + maxPoints,
    width: 420,
    height: 300,
    elements: [] // will be filled with enchant rows
  };

  // Populate enchant rows
  CUSTOM_ENCHANTS.forEach((ench, idx) => {
    const currentLevel = currentData.enchants[ench.id] || 0;
    const row = {
      type: "enchantRow",
      id: "ench_" + ench.id,
      name: ench.name,
      desc: ench.shortDesc,
      costPerLevel: ench.costPerLevel,
      maxLevel: ench.maxLevel,
      currentLevel: currentLevel,
      // slider: we model as {value, min, max}
      slider: { value: currentLevel, min: 0, max: ench.maxLevel, onChange: function(newVal) {
        // The GUI runtime should call updatePoints after modifying this value
      }}
    };
    gui.elements.push(row);
  });

  // Buttons
  gui.applyButton = { id: "apply", label: "Apply", onClick: function(state) {
    // state will include chosen levels
  }};
  gui.cancelButton = { id: "cancel", label: "Cancel" };

  // Tooltip note
  gui.note = "Trench Pickaxe will not break blocks below your current Y coordinate.";

  // In a real loader, we would create actual interactive sliders. Here we return the description object.
  return { guiDef: gui, maxPoints: maxPoints, pickaxeData: currentData };
}

/* =========================
   MATH & ORIENTATION: computing oriented trench box
   ========================= */

/**
 * Compute the oriented rectangular prism (axis-aligned in local forward/right/up space)
 * that represents the trench volume to break, given:
 *   - player position (x,y,z)
 *   - yaw, pitch (degrees)
 *   - trench dimensions (xWidth, yHeight, zDepth) where x is horizontal-left-right, y is vertical, z is forward depth
 *
 * Important rules:
 *   - Never include blocks whose global Y (blockY) is < Math.floor(playerY).
 *   - If pitch is strongly downward, shift box forward/down but still exclude below player's Y.
 *
 * Returns an array of block coordinates to consider breaking: [{x,y,z},...]
 */
function computeTrenchBoxBlocks(world, playerPos, yawDeg, pitchDeg, dims) {
  // Convert yaw/pitch to forward/right/up vectors (unit)
  const yaw = yawDeg * Math.PI / 180;
  const pitch = pitchDeg * Math.PI / 180;

  // forward vector
  const fx = -Math.sin(yaw) * Math.cos(pitch);
  const fy = -Math.sin(pitch);
  const fz = Math.cos(yaw) * Math.cos(pitch);

  // approximate right vector (perpendicular to forward)
  const rx = Math.cos(yaw);
  const rz = Math.sin(yaw);
  const ry = 0;

  // up vector cross product of right and forward
  const ux = fy * rz - fz * ry;
  const uy = fz * rx - fx * rz;
  const uz = fx * ry - fy * rx;
  // normalize up (approx)
  const upLen = Math.sqrt(ux*ux + uy*uy + uz*uz) || 1;
  const uxN = ux / upLen, uyN = uy / upLen, uzN = uz / upLen;

  // We'll iterate integer offsets inside local box coordinates and map to world coordinates.
  // dims.x: horizontal width (we'll center it around 0), dims.y: vertical height (we'll center on player's y or slightly above),
  // dims.z: depth forward (starting from the block the player is looking at or from player's feet forward).

  // Determine base origin: the nearest block in front of player at player's Y (clamped)
  const playerBlockY = Math.floor(playerPos.y);
  // We'll start from player's eye-level / feet depending on pitch.
  const startX = Math.floor(playerPos.x);
  const startY = playerBlockY; // trench will not include below this
  const startZ = Math.floor(playerPos.z);

  // We'll compute center offsets: x offsets in [-halfX..halfX], y offsets [0..dims.y-1] (no below), z offsets [1..dims.z] forward
  const halfX = Math.floor(dims.x / 2);
  const halfZ = Math.floor(dims.z); // depth starting forward (1..dims.z)

  const blocks = [];

  // For each local coordinate, map to world coordinate
  for (let lx = -halfX; lx <= halfX; lx++) {
    for (let lz = 1; lz <= dims.z; lz++) {
      for (let ly = 0; ly < dims.y; ly++) {
        // local vector = rx*lx + ux*ly + fx*lz
        const worldDX = rx * lx + uxN * ly + fx * lz;
        const worldDY = ry * lx + uyN * ly + fy * lz;
        const worldDZ = rz * lx + uzN * ly + fz * lz;

        const bx = Math.floor(playerPos.x + worldDX + 0.5);
        const by = Math.floor(playerPos.y + worldDY); // floor ensures we clamp below separately
        const bz = Math.floor(playerPos.z + worldDZ + 0.5);

        // Enforce not below player's Y coordinate
        if (by < playerBlockY) continue;

        // Avoid duplicates
        const key = bx + "," + by + "," + bz;
        blocks.push({ x: bx, y: by, z: bz, key: key });
      }
    }
  }

  // De-duplicate
  const unique = {};
  const result = [];
  blocks.forEach(b => {
    if (!unique[b.key]) {
      unique[b.key] = true;
      result.push({ x: b.x, y: b.y, z: b.z });
    }
  });

  return result;
}

/* =========================
   HELPER: compute max points by tier
   ========================= */
function computeMaxPointsForTier(tierIndex) {
  // tierIndex: 1..5 (1 wood, 5 diamond). Apply linear scaling:
  // points = WOOD_MAX_POINTS + (DIAMOND_MAX_POINTS - WOOD_MAX_POINTS) * ((tierIndex - 1) / (5 - 1))
  const ratio = (tierIndex - 1) / (5 - 1);
  const points = WOOD_MAX_POINTS + (DIAMOND_MAX_POINTS - WOOD_MAX_POINTS) * ratio;
  // Round to integer
  return Math.floor(points);
}

/* =========================
   BLOCK-BREAK HOOK: perform trench break when player breaks with a Trench Pickaxe
   ========================= */

// onBlockHarvested event signature assumed: function(event) where event has:
//   event.player, event.world, event.x, event.y, event.z, event.block, event.itemInHand
onBlockHarvested(function(event) {
  try {
    const player = event.player;
    const world = event.world;
    const item = event.itemInHand;
    if (!item) return;

    // Check if item is one of the trench pickaxes
    const isTrenchPick = Object.values(IDS.pickaxes).indexOf(item.id) !== -1;
    if (!isTrenchPick) return;

    // Safety: check if player is sneaking? (optional) We'll allow always.
    // Determine material id and dimensions
    const matId = item.toolMaterial || "wood";
    const dims = TRENCH_DIMENSIONS[matId] || TRENCH_DIMENSIONS.wood;

    // Compute forward ray/origin from player
    const playerPos = getPlayerPos(player);
    const yp = getPlayerYawPitch(player);
    // Compute trenches blocks to attempt to break (oriented)
    const candidateBlocks = computeTrenchBoxBlocks(world, playerPos, yp.yaw, yp.pitch, dims);

    // Read pickaxe data (enchants, durability)
    const pickData = getPickaxeData(item);

    // Compute effective parameters from enchants (e.g., trenching may expand horizontal dimension)
    const trenchLevel = pickData.enchants && pickData.enchants.trenching || 0;
    // For each trenching level, expand horizontal by +1 per level (example). We'll adjust dims locally.
    const effectiveDims = { x: dims.x + trenchLevel * 2, y: dims.y, z: dims.z };

    // If trenching expanded, recompute blocks - simpler approach: we'll filter candidateBlocks to those within expanded X radius
    // (Because computeTrenchBoxBlocks used base dims, a full accurate re-orientation would recompute; we approximate here.)
    // For real implementation, call computeTrenchBoxBlocks again with expanded dims:
    const candidateBlocks2 = computeTrenchBoxBlocks(world, playerPos, yp.yaw, yp.pitch, effectiveDims);

    // Harvestability and permissions checks:
    const blocksToBreak = [];
    candidateBlocks2.forEach(b => {
      const block = getBlockAt(world, b.x, b.y, b.z);
      if (!block) return;
      // Do not break air
      if (block.id === "minecraft:air") return;
      // Do not break bedrock
      if (block.id === "minecraft:bedrock") return;
      // Do not break if below player's Y - computeTrenchBoxBlocks already guaranteed but double-check
      if (b.y < Math.floor(playerPos.y)) return;
      // Respect harvest level: avoid blocks that this material cannot harvest
      if (!canHarvestBlockWithMaterial(block, matId)) return;
      // Respect server protections: placeholder function isBlockProtected(world,x,y,z,player)
      if (typeof isBlockProtected === "function" && isBlockProtected(world, b.x, b.y, b.z, player)) return;
      blocksToBreak.push({ x: b.x, y: b.y, z: b.z, block: block });
    });

    if (blocksToBreak.length === 0) return;

    // Apply Depth Guard: check for blocks that would cause unsafe drops; remove them if Depth Guard is not high enough
    const depthGuardLevel = pickData.enchants && pickData.enchants.depth_guard || 0;
    const finalBlocks = [];
    for (let i = 0; i < blocksToBreak.length; i++) {
      const b = blocksToBreak[i];
      // For simplicity: if breaking this block would remove supporting block under a block the player stands on,
      // or create a drop more than a threshold (e.g., 6 blocks), skip if depthGuard insufficient.
      const dropRisk = estimateDropRisk(world, b.x, b.y, b.z); // returns an integer drop risk
      if (dropRisk > (3 + depthGuardLevel * 2)) {
        // skip
        continue;
      }
      finalBlocks.push(b);
    }

    // Simulate durability usage per block and apply Fortitude enchant (reduces durability cost)
    const fortitudeLevel = pickData.enchants && pickData.enchants.fortitude || 0;
    const durabilityReduction = fortitudeLevel * 0.33; // each level reduces durability cost by 33% (example)
    let durabilityUsed = 0;

    // Conserve enchant: chance to convert drops into XP instead of items
    const conserveLevel = pickData.enchants && pickData.enchants.conserve || 0;

    // Fortitude: reduce durability cost per block
    finalBlocks.forEach(b => {
      // Simulate breaking the block: drop items, xp, etc.
      // Respect Vein Seek: if block is ore and vein_seek triggers, attempt to break neighboring connected ore blocks
      const isOre = isBlockOre(b.block);
      if (isOre && (pickData.enchants && pickData.enchants.vein_seek)) {
        // chance to include connected ore based on level
        const vsLevel = pickData.enchants.vein_seek;
        const extra = attemptVeinBreak(world, b.x, b.y, b.z, vsLevel);
        // extra is array of blocks added
        extra.forEach(eb => finalBlocks.push(eb));
      }

      // Break block
      const success = breakBlockWithDrops(world, b.x, b.y, b.z, player, /*dropItems=*/(conserveLevel === 0));
      if (success) {
        // durability cost baseline 1 per block
        let cost = 1;
        cost = Math.max(0, cost - durabilityReduction);
        durabilityUsed += cost;
        // If conserve enchant present, convert some drops to XP
        if (conserveLevel > 0) {
          const convertChance = 0.1 * conserveLevel; // 10% per level
          if (Math.random() < convertChance) {
            // convert: instead of dropping items, drop xp orbs at block position
            dropXp(world, b.x + 0.5, b.y + 0.5, b.z + 0.5, Math.max(1, Math.floor(Math.random() * 5 * conserveLevel)));
            // Optionally remove item drops: implemented by breakBlockWithDrops when conserve toggled
          }
        }
      }
    });

    // Apply durability deduction to the item
    if (typeof reduceItemDurability === "function") {
      reduceItemDurability(item, Math.ceil(durabilityUsed));
    } else {
      // adjust NBT fallback
      const pd = getPickaxeData(item);
      pd.durability = pd.durability - Math.ceil(durabilityUsed);
      if (pd.durability < 0) pd.durability = 0;
      setPickaxeData(item, pd);
    }

    // Trigger Echo Scrape: visual particles if ores nearby
    const echoLevel = pickData.enchants && pickData.enchants.echo_scrape || 0;
    if (echoLevel > 0) {
      // spawn particle effects near ore blocks within some radius
      pulseNearbyOreParticles(world, playerPos, echoLevel);
    }

    // Award XP for breaking blocks (simple simulation)
    const totalXp = Math.floor(finalBlocks.length * 0.5);
    if (totalXp > 0) dropXp(world, playerPos.x, playerPos.y, playerPos.z, totalXp);

    // Prevent default single-block break if we've broken multiple blocks; some engines require cancelling original event.
    if (typeof event.setCancelled === "function") event.setCancelled(true);

  } catch (e) {
    console.error("Trench mod block harvest handler error:", e);
  }
});

/* =========================
   Helper functions used by the block-break logic
   (These are pseudo-implementations and should be replaced/adapted
    to your server/client API for reliable behavior.)
   ========================= */

function getBlockAt(world, x, y, z) {
  if (typeof world.getBlock === "function") return world.getBlock(x, y, z);
  // fallback: return a dummy object
  return { id: "minecraft:stone", hardness: 1.5, name: "Stone" };
}

function canHarvestBlockWithMaterial(block, materialId) {
  // Simplified mapping: wood/stone can't harvest diamond ore; iron/diamond can. Gold acts like wood in harvest level on many 1.8 contexts.
  const harvestLevels = {
    "minecraft:diamond_ore": 3,
    "minecraft:gold_ore": 2,
    "minecraft:iron_ore": 1,
    "minecraft:coal_ore": 0,
    "minecraft:stone": 0,
    "minecraft:obsidian": 3
  };
  const required = harvestLevels[block.id] !== undefined ? harvestLevels[block.id] : 0;
  const matLevel = materialId === "wood" ? 0 : materialId === "stone" ? 1 : materialId === "iron" ? 2 : materialId === "gold" ? 0 : 3;
  return matLevel >= required;
}

function estimateDropRisk(world, x, y, z) {
  // Very rough estimation: count empty blocks beneath within 6 blocks
  let risk = 0;
  for (let d = 1; d <= 6; d++) {
    const b = getBlockAt(world, x, y - d, z);
    if (!b || b.id === "minecraft:air") risk++;
    else break;
  }
  return risk;
}

function isBlockOre(block) {
  return block.id && (block.id.indexOf("_ore") !== -1 || block.id.indexOf("ore") !== -1);
}

function attemptVeinBreak(world, x, y, z, veinLevel) {
  // naive BFS up to a small radius; returns array of block coords to add
  const found = [];
  const visited = {};
  const stack = [{ x: x, y: y, z: z }];
  const maxNodes = 8 + veinLevel * 8;
  while (stack.length && found.length < maxNodes) {
    const c = stack.pop();
    const key = c.x + "," + c.y + "," + c.z;
    if (visited[key]) continue;
    visited[key] = true;
    const b = getBlockAt(world, c.x, c.y, c.z);
    if (!b) continue;
    if (isBlockOre(b)) {
      found.push({ x: c.x, y: c.y, z: c.z, block: b });
      // push neighbors
      const nbs = [
        { x: c.x+1, y: c.y, z: c.z }, { x: c.x-1, y: c.y, z: c.z },
        { x: c.x, y: c.y+1, z: c.z }, { x: c.x, y: c.y-1, z: c.z },
        { x: c.x, y: c.y, z: c.z+1 }, { x: c.x, y: c.y, z: c.z-1 }
      ];
      nbs.forEach(nb => {
        if (!visited[nb.x + "," + nb.y + "," + nb.z]) stack.push(nb);
      });
    }
  }
  return found;
}

function breakBlockWithDrops(world, x, y, z, player, dropItems) {
  // Placeholder: call world.breakBlock or similar
  if (typeof world.breakBlock === "function") {
    try {
      world.breakBlock(x, y, z, dropItems);
      return true;
    } catch (e) {
      return false;
    }
  } else {
    // simulate by logging
    console.log("Breaking block at", x, y, z, "dropItems:", dropItems);
    return true;
  }
}

function dropXp(world, x, y, z, amount) {
  if (typeof world.spawnXp === "function") {
    world.spawnXp(x, y, z, amount);
  } else {
    console.log("Drop XP", amount, "at", x, y, z);
  }
}

function reduceItemDurability(itemStack, amount) {
  // Placeholder: many loaders provide itemStack.damage(amount)
  if (typeof itemStack.damage === "function") {
    itemStack.damage(amount);
  } else {
    // fallback to NBT
    const pd = getPickaxeData(itemStack);
    pd.durability = (pd.durability || itemStack.maxDurability) - amount;
    if (pd.durability < 0) pd.durability = 0;
    setPickaxeData(itemStack, pd);
  }
}

function pulseNearbyOreParticles(world, playerPos, echoLevel) {
  // For each ore within radius R, spawn particle at approximate location. R scales with echoLevel.
  const R = 6 + echoLevel * 4;
  if (typeof world.findBlocksWithinRadius !== "function") {
    // fallback console
    console.log("Pulse ore particles around", playerPos, "radius", R);
    return;
  }
  const ores = world.findBlocksWithinRadius(playerPos.x, playerPos.y, playerPos.z, R, function(b) {
    return isBlockOre(b);
  });
  ores.forEach(o => {
    if (typeof world.spawnParticle === "function") {
      world.spawnParticle("enchant", o.x + 0.5, o.y + 0.5, o.z + 0.5);
    }
  });
}

/* =========================
   GUI: Implementation sketch for the Trench Enchanter interactive UI
   =========================
   Note: Real GUI implementation depends on platform. Below is a working pseudo-logic
   to show how to handle sliders, point budgeting, apply/cancel and NBT persistence.
   ========================= */

function openTrenchEnchanterForPlayer(player, blockPos) {
  // Get held item in player's hand
  const heldItem = player.getHeldItem ? player.getHeldItem() : player.itemInHand;
  if (!heldItem) {
    sendMessage(player, "You must hold a Trench Pickaxe to enchant it.");
    return;
  }
  if (Object.values(IDS.pickaxes).indexOf(heldItem.id) === -1) {
    sendMessage(player, "You must hold a Trench Pickaxe to use the Trench Enchanter.");
    return;
  }

  const guiInfo = createTrenchEnchanterGui(player, heldItem);
  // The GUI runtime should present interactive sliders and call back to us on events.
  // We'll register callback handlers in a pseudo-fashion.

  openGui(player, {
    title: guiInfo.guiDef.title,
    subtitle: "Points: 0 / " + guiInfo.maxPoints,
    width: guiInfo.guiDef.width,
    height: guiInfo.guiDef.height,
    elements: guiInfo.guiDef.elements,
    note: guiInfo.guiDef.note,
    onSliderChange: function(playerState, enchantId, newValue) {
      // playerState: {selectedLevels: {enchId: level, ...}}
      playerState.selectedLevels = playerState.selectedLevels || {};
      playerState.selectedLevels[enchantId] = newValue;
      // Recompute total used points
      const used = computePointsUsed(playerState.selectedLevels);
      // Push an update to the GUI (pseudo)
      return { used: used, max: guiInfo.maxPoints, ok: used <= guiInfo.maxPoints };
    },
    onApply: function(playerState) {
      const selected = playerState.selectedLevels || {};
      const used = computePointsUsed(selected);
      if (used > guiInfo.maxPoints) {
        sendMessage(player, "Selected enchant levels exceed this pickaxe's point budget (" + used + " > " + guiInfo.maxPoints + ").");
        return { success: false, message: "Not enough points." };
      }
      // Persist enchants to the held item NBT
      const pd = getPickaxeData(heldItem);
      pd.enchants = pd.enchants || {};
      Object.keys(selected).forEach(eid => {
        const lvl = selected[eid] || 0;
        if (lvl <= 0) delete pd.enchants[eid];
        else pd.enchants[eid] = lvl;
      });
      setPickaxeData(heldItem, pd);
      // Optionally consume player XP or items as cost. If no XP support, require trench_gem_green as cost (example).
      // For simplicity here, we do not consume XP in code; adapt as needed.
      sendMessage(player, "Applied trench enchants. Points used: " + used + " / " + guiInfo.maxPoints);
      return { success: true };
    },
    onCancel: function() {
      sendMessage(player, "Trench Enchanter: cancelled.");
      return { success: true };
    }
  });
}

function computePointsUsed(selectedLevels) {
  selectedLevels = selectedLevels || {};
  let total = 0;
  for (let i = 0; i < CUSTOM_ENCHANTS.length; i++) {
    const e = CUSTOM_ENCHANTS[i];
    const lvl = selectedLevels[e.id] || 0;
    total += lvl * e.costPerLevel;
  }
  return total;
}

/* ===========
   BLOCK INTERACTION: open GUI when player right-clicks the trench enchanter block
   =========== */
if (typeof onBlockRightClick === "function") {
  onBlockRightClick(function(event) {
    const b = event.block;
    if (!b) return;
    if (b.id === IDS.trench_enchanter) {
      openTrenchEnchanterForPlayer(event.player, { x: event.x, y: event.y, z: event.z });
      if (typeof event.setCancelled === "function") event.setCancelled(true);
    }
  });
}

/* =========================
   SIMPLE ADMIN / DEBUG COMMANDS (optional)
   ========================= */
if (typeof registerCommand === "function") {
  registerCommand("trenchinfo", function(sender, args) {
    // show enchant and point info for held pickaxe
    const item = sender.getHeldItem ? sender.getHeldItem() : sender.itemInHand;
    if (!item) {
      sendMessage(sender, "Hold a Trench Pickaxe to see info.");
      return;
    }
    const pd = getPickaxeData(item);
    const matId = item.toolMaterial || "wood";
    const tier = MATERIAL_TIERS[matId === "wood" ? 1 : matId === "stone" ? 2 : matId === "iron" ? 3 : matId === "gold" ? 4 : 5];
    const maxPoints = computeMaxPointsForTier(tier.tierIndex);
    sendMessage(sender, "Trench Pickaxe: " + matId + " | Points: " + maxPoints);
    sendMessage(sender, "Enchants: " + JSON.stringify(pd.enchants));
  });
}

/* =========================
   END OF MOD FILE
   ========================= */

/* =========================
   SHORT SUMMARY / ACTION ITEMS (3–6 bullets)
   =========================
   - Drop this file as trench_mod.js into your server/client mods folder for your JS-enabled 1.8.8 mod loader.
   - Place textures under: assets/trenchmod/textures/items/ and assets/trenchmod/textures/blocks/ as named at the top.
   - If your loader's API names differ, adapt the wrapper functions at the top (registerItem, registerBlock, addShapedRecipe, onBlockHarvested, openGui).
   - To change the number of custom enchants, update NUMBER_OF_CUSTOM_ENCHANTS and the CUSTOM_ENCHANTS array; diamond maxPoints uses formula: 20 * N * 0.5.
   - For full visual GUI and particle behavior, wire the pseudo GUI callbacks (onSliderChange, onApply) to your client GUI runtime.
   ========================= */
